services:
  postgres:
    image: postgres:17.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./migrations/up.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      - PGADMIN_DEFAULT_PASSWORD=$(PGADMIN_DEFAULT_PASSWORD:-postgres}
      # PGADMIN_CONFIG_SERVER_MODE: False
      # PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: False
    ports:
      - "${PGADMIN_PORT:-15432}:80"
    volumes:
      - ./docker/pgAdmin/data:/var/lib/pgadmin
      - ./docker/pgAdmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    user: root

  marketplace:
    build: .
    restart: always
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
    ports:
      - "8000:5000"
    depends_on:
      - postgres

networks: 
  marketplace_default:
    driver: bridge

volumes:
  postgres:
  pgadmin:
